// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfkDWQR2kHkdtQ9TpcXiytafYyk37hjGw',
    appId: '1:872974730213:android:8aa51dcf5c2f2a4aa3e50c',
    messagingSenderId: '872974730213',
    projectId: 'whatsapp-clone-fe43c',
    storageBucket: 'whatsapp-clone-fe43c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6yfRHN2Vn8V1qHa1G8I1kJn43z-QqKaU',
    appId: '1:872974730213:ios:15c8a08b440e177ca3e50c',
    messagingSenderId: '872974730213',
    projectId: 'whatsapp-clone-fe43c',
    storageBucket: 'whatsapp-clone-fe43c.appspot.com',
    iosClientId: '872974730213-f0ql4lqo1h6d0tdj24u7rph21qsj41kt.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsappFlutter',
  );
}
